// Code generated by cmd/kodi-gen from schema/v12/types.json. DO NOT EDIT.

package v12

// Schema version 12.4.0.

import "github.com/ayasechan/kodigo/internal/rpc"

// APIMajor is the major Kodi JSON-RPC API version this package speaks.
// It is bumped on backwards incompatible changes to the API definition.
const APIMajor = 12

// APIMinor is the minor Kodi JSON-RPC API version this package was generated from.
// It is bumped on backwards compatible additions to the API definition.
const APIMinor = 4

// Client is a JSON-RPC client for Kodi API v12 (schema version 12.4.0).
// The transport is shared with all API versions; see the rpc package.
type Client struct {
	*rpc.Client
}

// NewClient creates a Client targeting endpoint (e.g. "http://localhost:8080/jsonrpc").
func NewClient(endpoint string, opts ...rpc.Option) *Client {
	return &Client{Client: rpc.NewClient(endpoint, opts...)}
}

// Wrap adapts an existing shared transport client (e.g. after version
// negotiation) to this API version.
func Wrap(c *rpc.Client) *Client {
	return &Client{Client: c}
}

// Compile-time guarantee that the versioned client satisfies rpc.Caller,
// so it works with version-agnostic helpers (negotiation, …).
var _ rpc.Caller = (*Client)(nil)
