// Code generated by cmd/kodi-gen from schema/v12/types.json. DO NOT EDIT.

package v12

// Schema version 12.4.0.

// SchemaVersion is the Kodi JSON-RPC schema version (schema/version.txt)
// this package was generated from.
const SchemaVersion = "12.4.0"

// Nullable bool.
type OptionalBoolean bool

// Nullable string.
type OptionalString string

// Nullable int.
type OptionalInteger int

// Nullable float64.
type OptionalNumber float64

type ArrayString []string

type ArrayInteger []int

// A duration.
type GlobalTime struct {
	Hours        int `json:"hours"`
	Milliseconds int `json:"milliseconds"`
	Minutes      int `json:"minutes"`
	Seconds      int `json:"seconds"`
}

type GlobalWeekday string

const (
	GlobalWeekdayMonday    GlobalWeekday = "monday"
	GlobalWeekdayTuesday   GlobalWeekday = "tuesday"
	GlobalWeekdayWednesday GlobalWeekday = "wednesday"
	GlobalWeekdayThursday  GlobalWeekday = "thursday"
	GlobalWeekdayFriday    GlobalWeekday = "friday"
	GlobalWeekdaySaturday  GlobalWeekday = "saturday"
	GlobalWeekdaySunday    GlobalWeekday = "sunday"
)

type GlobalIncrementDecrement string

const (
	GlobalIncrementDecrementIncrement GlobalIncrementDecrement = "increment"
	GlobalIncrementDecrementDecrement GlobalIncrementDecrement = "decrement"
)

// GlobalToggle is a union; decoded as any. See schema key "Global.Toggle" in types.json.
type GlobalToggle any

type GlobalStringNotEmpty string

type ConfigurationNotifications struct {
	Application  bool `json:"Application"`
	AudioLibrary bool `json:"AudioLibrary"`
	GUI          bool `json:"GUI"`
	Input        bool `json:"Input"`
	Other        bool `json:"Other"`
	PVR          bool `json:"PVR"`
	Player       bool `json:"Player"`
	Playlist     bool `json:"Playlist"`
	System       bool `json:"System"`
	VideoLibrary bool `json:"VideoLibrary"`
}

type Configuration struct {
	Notifications ConfigurationNotifications `json:"notifications"`
}

type FilesMedia string

const (
	FilesMediaVideo    FilesMedia = "video"
	FilesMediaMusic    FilesMedia = "music"
	FilesMediaPictures FilesMedia = "pictures"
	FilesMediaFiles    FilesMedia = "files"
	FilesMediaPrograms FilesMedia = "programs"
)

// Default: -1.
type ListAmount int

type ListLimits struct {
	// Index of the last item to return
	End *ListAmount `json:"end,omitempty"`
	// Index of the first item to return
	// Default: 0.
	Start *int `json:"start,omitempty"`
}

type ListLimitsReturned struct {
	End *ListAmount `json:"end,omitempty"`
	// Default: 0.
	Start *int `json:"start,omitempty"`
	Total int  `json:"total"`
}

type ListSort struct {
	// Default: false.
	Ignorearticle *bool `json:"ignorearticle,omitempty"`
	// Default: none.
	Method *string `json:"method,omitempty"`
	// Default: ascending.
	Order *string `json:"order,omitempty"`
	// Default: false.
	Useartistsortname *bool `json:"useartistsortname,omitempty"`
}

// Default: -1.
type LibraryID int

type PVRChannelType string

const (
	PVRChannelTypeTV    PVRChannelType = "tv"
	PVRChannelTypeRadio PVRChannelType = "radio"
)

// Default: -1.
type PlaylistID int

type PlaylistType string

const (
	PlaylistTypeUnknown PlaylistType = "unknown"
	PlaylistTypeVideo   PlaylistType = "video"
	PlaylistTypeAudio   PlaylistType = "audio"
	PlaylistTypePicture PlaylistType = "picture"
	PlaylistTypeMixed   PlaylistType = "mixed"
)

type PlaylistPropertyName string

const (
	PlaylistPropertyNameType PlaylistPropertyName = "type"
	PlaylistPropertyNameSize PlaylistPropertyName = "size"
)

type PlaylistPropertyValue struct {
	Size *int          `json:"size,omitempty"`
	Type *PlaylistType `json:"type,omitempty"`
}

// Default: -1.
type PlaylistPosition int

// PlaylistItem is a union; decoded as any. See schema key "Playlist.Item" in types.json.
type PlaylistItem any

// Default: -1.
type PlayerID int

type PlayerType string

const (
	PlayerTypeVideo   PlayerType = "video"
	PlayerTypeAudio   PlayerType = "audio"
	PlayerTypePicture PlayerType = "picture"
)

type PlayerPositionPercentage float64

// A position in duration.
type PlayerPositionTime struct {
	// Default: 0.
	Hours *int `json:"hours,omitempty"`
	// Default: 0.
	Milliseconds *int `json:"milliseconds,omitempty"`
	// Default: 0.
	Minutes *int `json:"minutes,omitempty"`
	// Default: 0.
	Seconds *int `json:"seconds,omitempty"`
}

type PlayerSpeed struct {
	Speed *int `json:"speed,omitempty"`
}

type PlayerViewMode string

const (
	PlayerViewModeNormal            PlayerViewMode = "normal"
	PlayerViewModeZoom              PlayerViewMode = "zoom"
	PlayerViewModeStretch4x3        PlayerViewMode = "stretch4x3"
	PlayerViewModeWidezoom          PlayerViewMode = "widezoom"
	PlayerViewModeStretch16x9       PlayerViewMode = "stretch16x9"
	PlayerViewModeOriginal          PlayerViewMode = "original"
	PlayerViewModeStretch16x9nonlin PlayerViewMode = "stretch16x9nonlin"
	PlayerViewModeZoom120width      PlayerViewMode = "zoom120width"
	PlayerViewModeZoom110width      PlayerViewMode = "zoom110width"
)

type PlayerCustomViewMode struct {
	Nonlinearstretch any `json:"nonlinearstretch,omitempty"`
	Pixelratio       any `json:"pixelratio,omitempty"`
	Verticalshift    any `json:"verticalshift,omitempty"`
	Zoom             any `json:"zoom,omitempty"`
}

type PlayerRepeat string

const (
	PlayerRepeatOff PlayerRepeat = "off"
	PlayerRepeatOne PlayerRepeat = "one"
	PlayerRepeatAll PlayerRepeat = "all"
)

type PlayerAudioStream struct {
	Bitrate    int    `json:"bitrate"`
	Channels   int    `json:"channels"`
	Codec      string `json:"codec"`
	Index      int    `json:"index"`
	Isdefault  bool   `json:"isdefault"`
	Isimpaired bool   `json:"isimpaired"`
	Isoriginal bool   `json:"isoriginal"`
	Language   string `json:"language"`
	Name       string `json:"name"`
	Samplerate int    `json:"samplerate"`
}

type PlayerVideoStream struct {
	Codec    string `json:"codec"`
	Height   int    `json:"height"`
	Index    int    `json:"index"`
	Language string `json:"language"`
	Name     string `json:"name"`
	Width    int    `json:"width"`
}

type PlayerSubtitle struct {
	Index      int    `json:"index"`
	Isdefault  bool   `json:"isdefault"`
	Isforced   bool   `json:"isforced"`
	Isimpaired bool   `json:"isimpaired"`
	Language   string `json:"language"`
	Name       string `json:"name"`
}

type PlayerPropertyName string

const (
	PlayerPropertyNameType               PlayerPropertyName = "type"
	PlayerPropertyNamePartymode          PlayerPropertyName = "partymode"
	PlayerPropertyNameSpeed              PlayerPropertyName = "speed"
	PlayerPropertyNameTime               PlayerPropertyName = "time"
	PlayerPropertyNamePercentage         PlayerPropertyName = "percentage"
	PlayerPropertyNameTotaltime          PlayerPropertyName = "totaltime"
	PlayerPropertyNamePlaylistID         PlayerPropertyName = "playlistid"
	PlayerPropertyNamePosition           PlayerPropertyName = "position"
	PlayerPropertyNameRepeat             PlayerPropertyName = "repeat"
	PlayerPropertyNameShuffled           PlayerPropertyName = "shuffled"
	PlayerPropertyNameCanseek            PlayerPropertyName = "canseek"
	PlayerPropertyNameCanchangespeed     PlayerPropertyName = "canchangespeed"
	PlayerPropertyNameCanmove            PlayerPropertyName = "canmove"
	PlayerPropertyNameCanzoom            PlayerPropertyName = "canzoom"
	PlayerPropertyNameCanrotate          PlayerPropertyName = "canrotate"
	PlayerPropertyNameCanshuffle         PlayerPropertyName = "canshuffle"
	PlayerPropertyNameCanrepeat          PlayerPropertyName = "canrepeat"
	PlayerPropertyNameCurrentaudiostream PlayerPropertyName = "currentaudiostream"
	PlayerPropertyNameAudiostreams       PlayerPropertyName = "audiostreams"
	PlayerPropertyNameSubtitleenabled    PlayerPropertyName = "subtitleenabled"
	PlayerPropertyNameCurrentsubtitle    PlayerPropertyName = "currentsubtitle"
	PlayerPropertyNameSubtitles          PlayerPropertyName = "subtitles"
	PlayerPropertyNameLive               PlayerPropertyName = "live"
	PlayerPropertyNameCurrentvideostream PlayerPropertyName = "currentvideostream"
	PlayerPropertyNameVideostreams       PlayerPropertyName = "videostreams"
	PlayerPropertyNameCachepercentage    PlayerPropertyName = "cachepercentage"
)

type PlayerPropertyValue struct {
	Audiostreams       []PlayerAudioStream       `json:"audiostreams,omitempty"`
	Cachepercentage    *PlayerPositionPercentage `json:"cachepercentage,omitempty"`
	Canchangespeed     *bool                     `json:"canchangespeed,omitempty"`
	Canmove            *bool                     `json:"canmove,omitempty"`
	Canrepeat          *bool                     `json:"canrepeat,omitempty"`
	Canrotate          *bool                     `json:"canrotate,omitempty"`
	Canseek            *bool                     `json:"canseek,omitempty"`
	Canshuffle         *bool                     `json:"canshuffle,omitempty"`
	Canzoom            *bool                     `json:"canzoom,omitempty"`
	Currentaudiostream *PlayerAudioStream        `json:"currentaudiostream,omitempty"`
	Currentsubtitle    *PlayerSubtitle           `json:"currentsubtitle,omitempty"`
	Currentvideostream *PlayerVideoStream        `json:"currentvideostream,omitempty"`
	Live               *bool                     `json:"live,omitempty"`
	Partymode          *bool                     `json:"partymode,omitempty"`
	Percentage         *PlayerPositionPercentage `json:"percentage,omitempty"`
	PlaylistID         *PlaylistID               `json:"playlistid,omitempty"`
	Position           *PlaylistPosition         `json:"position,omitempty"`
	Repeat             *PlayerRepeat             `json:"repeat,omitempty"`
	Shuffled           *bool                     `json:"shuffled,omitempty"`
	Speed              *int                      `json:"speed,omitempty"`
	Subtitleenabled    *bool                     `json:"subtitleenabled,omitempty"`
	Subtitles          []PlayerSubtitle          `json:"subtitles,omitempty"`
	Time               *GlobalTime               `json:"time,omitempty"`
	Totaltime          *GlobalTime               `json:"totaltime,omitempty"`
	Type               *PlayerType               `json:"type,omitempty"`
	Videostreams       []PlayerVideoStream       `json:"videostreams,omitempty"`
}

type NotificationsItemType string

const (
	NotificationsItemTypeUnknown    NotificationsItemType = "unknown"
	NotificationsItemTypeMovie      NotificationsItemType = "movie"
	NotificationsItemTypeEpisode    NotificationsItemType = "episode"
	NotificationsItemTypeMusicvideo NotificationsItemType = "musicvideo"
	NotificationsItemTypeSong       NotificationsItemType = "song"
	NotificationsItemTypePicture    NotificationsItemType = "picture"
	NotificationsItemTypeChannel    NotificationsItemType = "channel"
)

// NotificationsItem is a union; decoded as any. See schema key "Notifications.Item" in types.json.
type NotificationsItem any

type PlayerNotificationsPlayer struct {
	PlayerID PlayerID `json:"playerid"`
	Speed    *int     `json:"speed,omitempty"`
}

type PlayerNotificationsPlayerSeek struct {
	PlayerNotificationsPlayer             // embedded base type Player.Notifications.Player
	Seekoffset                *GlobalTime `json:"seekoffset,omitempty"`
	Time                      *GlobalTime `json:"time,omitempty"`
}

type PlayerNotificationsData struct {
	Item   NotificationsItem         `json:"item"`
	Player PlayerNotificationsPlayer `json:"player"`
}

type ItemFieldsBase []string

type ItemDetailsBase struct {
	Label string `json:"label"`
}

type ItemCustomProperties struct {
}

type MediaDetailsBase struct {
	ItemDetailsBase         // embedded base type Item.Details.Base
	Fanart          *string `json:"fanart,omitempty"`
	Thumbnail       *string `json:"thumbnail,omitempty"`
}

type MediaArtwork struct {
	Banner *GlobalStringNotEmpty `json:"banner,omitempty"`
	Fanart *GlobalStringNotEmpty `json:"fanart,omitempty"`
	Poster *GlobalStringNotEmpty `json:"poster,omitempty"`
	Thumb  *GlobalStringNotEmpty `json:"thumb,omitempty"`
}

type MediaArtworkSet struct {
	// Default: .
	Banner *GlobalStringNotEmpty `json:"banner,omitempty"`
	// Default: .
	Fanart *GlobalStringNotEmpty `json:"fanart,omitempty"`
	// Default: .
	Poster *GlobalStringNotEmpty `json:"poster,omitempty"`
	// Default: .
	Thumb *GlobalStringNotEmpty `json:"thumb,omitempty"`
}

type VideoRating struct {
	Default *bool   `json:"default,omitempty"`
	Rating  float64 `json:"rating"`
	Votes   *int    `json:"votes,omitempty"`
}

type VideoRatings struct {
}

type VideoRatingsSet struct {
}

type MediaUniqueID struct {
}

type MediaUniqueIDSet struct {
}

// Extends Item.Fields.Base.
type LibraryFieldsSource []string

type LibraryDetailsSource struct {
	ItemDetailsBase // embedded base type Item.Details.Base
	// The url encoded multipath string combining all paths of the source
	File string `json:"file"`
	// The individual paths of the media source
	Paths    ArrayString `json:"paths,omitempty"`
	SourceID LibraryID   `json:"sourceid"`
}

// Extends Item.Fields.Base.
type LibraryFieldsGenre []string

type LibraryDetailsGenre struct {
	ItemDetailsBase           // embedded base type Item.Details.Base
	GenreID         LibraryID `json:"genreid"`
	// The ids of sources with songs of the genre
	SourceID  ArrayInteger `json:"sourceid,omitempty"`
	Thumbnail *string      `json:"thumbnail,omitempty"`
	Title     *string      `json:"title,omitempty"`
}

// Extends Item.Fields.Base.
type LibraryFieldsTag []string

type LibraryDetailsTag struct {
	ItemDetailsBase           // embedded base type Item.Details.Base
	TagID           LibraryID `json:"tagid"`
	Title           *string   `json:"title,omitempty"`
}

// Extends Item.Fields.Base.
type AudioFieldsRole []string

type AudioDetailsRole struct {
	ItemDetailsBase           // embedded base type Item.Details.Base
	RoleID          LibraryID `json:"roleid"`
	Title           *string   `json:"title,omitempty"`
}

// Extends Item.Fields.Base.
type AudioFieldsArtist []string

// Extends Item.Fields.Base.
type AudioFieldsAlbum []string

// Extends Item.Fields.Base.
type AudioFieldsSong []string

type AudioAlbumReleaseType string

const (
	AudioAlbumReleaseTypeAlbum  AudioAlbumReleaseType = "album"
	AudioAlbumReleaseTypeSingle AudioAlbumReleaseType = "single"
)

type AudioContributors []map[string]any

type AudioArtistRoles []map[string]any

type AudioDetailsGenres []map[string]any

type AudioDetailsBase struct {
	MediaDetailsBase               // embedded base type Media.Details.Base
	Art              *MediaArtwork `json:"art,omitempty"`
	Dateadded        *string       `json:"dateadded,omitempty"`
	Genre            ArrayString   `json:"genre,omitempty"`
}

type AudioDetailsMedia struct {
	AudioDetailsBase                      // embedded base type Audio.Details.Base
	Artist                   ArrayString  `json:"artist,omitempty"`
	ArtistID                 ArrayInteger `json:"artistid,omitempty"`
	Displayartist            *string      `json:"displayartist,omitempty"`
	MusicbrainzalbumartistID ArrayString  `json:"musicbrainzalbumartistid,omitempty"`
	Originaldate             *string      `json:"originaldate,omitempty"`
	Rating                   *float64     `json:"rating,omitempty"`
	Releasedate              *string      `json:"releasedate,omitempty"`
	Sortartist               *string      `json:"sortartist,omitempty"`
	Title                    *string      `json:"title,omitempty"`
	Userrating               *int         `json:"userrating,omitempty"`
	Votes                    *int         `json:"votes,omitempty"`
	Year                     *int         `json:"year,omitempty"`
}

type AudioDetailsArtist struct {
	AudioDetailsBase                       // embedded base type Audio.Details.Base
	Artist              string             `json:"artist"`
	ArtistID            LibraryID          `json:"artistid"`
	Born                *string            `json:"born,omitempty"`
	Compilationartist   *bool              `json:"compilationartist,omitempty"`
	Description         *string            `json:"description,omitempty"`
	Died                *string            `json:"died,omitempty"`
	Disambiguation      *string            `json:"disambiguation,omitempty"`
	Disbanded           *string            `json:"disbanded,omitempty"`
	Formed              *string            `json:"formed,omitempty"`
	Gender              *string            `json:"gender,omitempty"`
	Instrument          ArrayString        `json:"instrument,omitempty"`
	Isalbumartist       *bool              `json:"isalbumartist,omitempty"`
	Mood                ArrayString        `json:"mood,omitempty"`
	MusicbrainzartistID ArrayString        `json:"musicbrainzartistid,omitempty"`
	Roles               AudioArtistRoles   `json:"roles,omitempty"`
	Songgenres          AudioDetailsGenres `json:"songgenres,omitempty"`
	Sortname            *string            `json:"sortname,omitempty"`
	SourceID            ArrayInteger       `json:"sourceid,omitempty"`
	Style               ArrayString        `json:"style,omitempty"`
	Type                *string            `json:"type,omitempty"`
	Yearsactive         ArrayString        `json:"yearsactive,omitempty"`
}

type AudioDetailsAlbum struct {
	AudioDetailsMedia                                // embedded base type Audio.Details.Media
	Albumduration             *int                   `json:"albumduration,omitempty"`
	AlbumID                   LibraryID              `json:"albumid"`
	Albumlabel                *string                `json:"albumlabel,omitempty"`
	Albumstatus               *string                `json:"albumstatus,omitempty"`
	Compilation               *bool                  `json:"compilation,omitempty"`
	Description               *string                `json:"description,omitempty"`
	Isboxset                  *bool                  `json:"isboxset,omitempty"`
	Lastplayed                *string                `json:"lastplayed,omitempty"`
	Mood                      ArrayString            `json:"mood,omitempty"`
	MusicbrainzalbumID        *string                `json:"musicbrainzalbumid,omitempty"`
	MusicbrainzreleasegroupID *string                `json:"musicbrainzreleasegroupid,omitempty"`
	Playcount                 *int                   `json:"playcount,omitempty"`
	Releasetype               *AudioAlbumReleaseType `json:"releasetype,omitempty"`
	Songgenres                AudioDetailsGenres     `json:"songgenres,omitempty"`
	SourceID                  ArrayInteger           `json:"sourceid,omitempty"`
	Style                     ArrayString            `json:"style,omitempty"`
	Theme                     ArrayString            `json:"theme,omitempty"`
	Totaldiscs                *int                   `json:"totaldiscs,omitempty"`
	Type                      *string                `json:"type,omitempty"`
}

type AudioDetailsSong struct {
	AudioDetailsMedia                          // embedded base type Audio.Details.Media
	Album               *string                `json:"album,omitempty"`
	Albumartist         ArrayString            `json:"albumartist,omitempty"`
	AlbumartistID       ArrayInteger           `json:"albumartistid,omitempty"`
	AlbumID             *LibraryID             `json:"albumid,omitempty"`
	Albumreleasetype    *AudioAlbumReleaseType `json:"albumreleasetype,omitempty"`
	Bitrate             *int                   `json:"bitrate,omitempty"`
	Bpm                 *int                   `json:"bpm,omitempty"`
	Channels            *int                   `json:"channels,omitempty"`
	Comment             *string                `json:"comment,omitempty"`
	Contributors        AudioContributors      `json:"contributors,omitempty"`
	Disc                *int                   `json:"disc,omitempty"`
	Disctitle           *string                `json:"disctitle,omitempty"`
	Displaycomposer     *string                `json:"displaycomposer,omitempty"`
	Displayconductor    *string                `json:"displayconductor,omitempty"`
	Displaylyricist     *string                `json:"displaylyricist,omitempty"`
	Displayorchestra    *string                `json:"displayorchestra,omitempty"`
	Duration            *int                   `json:"duration,omitempty"`
	File                *string                `json:"file,omitempty"`
	GenreID             ArrayInteger           `json:"genreid,omitempty"`
	Lastplayed          *string                `json:"lastplayed,omitempty"`
	Lyrics              *string                `json:"lyrics,omitempty"`
	Mood                *string                `json:"mood,omitempty"`
	MusicbrainzartistID ArrayString            `json:"musicbrainzartistid,omitempty"`
	MusicbrainztrackID  *string                `json:"musicbrainztrackid,omitempty"`
	Playcount           *int                   `json:"playcount,omitempty"`
	Samplerate          *int                   `json:"samplerate,omitempty"`
	SongID              LibraryID              `json:"songid"`
	SourceID            ArrayInteger           `json:"sourceid,omitempty"`
	Track               *int                   `json:"track,omitempty"`
}

type AudioPropertyName string

const (
	AudioPropertyNameMissingartistID    AudioPropertyName = "missingartistid"
	AudioPropertyNameLibrarylastupdated AudioPropertyName = "librarylastupdated"
	AudioPropertyNameLibrarylastcleaned AudioPropertyName = "librarylastcleaned"
	AudioPropertyNameArtistlinksupdated AudioPropertyName = "artistlinksupdated"
	AudioPropertyNameSongslastadded     AudioPropertyName = "songslastadded"
	AudioPropertyNameAlbumslastadded    AudioPropertyName = "albumslastadded"
	AudioPropertyNameArtistslastadded   AudioPropertyName = "artistslastadded"
	AudioPropertyNameGenreslastadded    AudioPropertyName = "genreslastadded"
	AudioPropertyNameSongsmodified      AudioPropertyName = "songsmodified"
	AudioPropertyNameAlbumsmodified     AudioPropertyName = "albumsmodified"
	AudioPropertyNameArtistsmodified    AudioPropertyName = "artistsmodified"
)

type AudioPropertyValue struct {
	Albumslastadded    *string    `json:"albumslastadded,omitempty"`
	Albumsmodified     *string    `json:"albumsmodified,omitempty"`
	Artistlinksupdated *string    `json:"artistlinksupdated,omitempty"`
	Artistslastadded   *string    `json:"artistslastadded,omitempty"`
	Artistsmodified    *string    `json:"artistsmodified,omitempty"`
	Genreslastadded    *string    `json:"genreslastadded,omitempty"`
	Librarylastcleaned *string    `json:"librarylastcleaned,omitempty"`
	Librarylastupdated *string    `json:"librarylastupdated,omitempty"`
	MissingartistID    *LibraryID `json:"missingartistid,omitempty"`
	Songslastadded     *string    `json:"songslastadded,omitempty"`
	Songsmodified      *string    `json:"songsmodified,omitempty"`
}

// Extends Item.Fields.Base.
type VideoFieldsMovie []string

// Extends Item.Fields.Base.
type VideoFieldsMovieSet []string

// Extends Item.Fields.Base.
type VideoFieldsTVShow []string

// Extends Item.Fields.Base.
type VideoFieldsSeason []string

// Extends Item.Fields.Base.
type VideoFieldsEpisode []string

// Extends Item.Fields.Base.
type VideoFieldsMusicVideo []string

type VideoCast []map[string]any

type VideoStreams struct {
	Audio    []VideoStreamsAudioItem    `json:"audio,omitempty"`
	Subtitle []VideoStreamsSubtitleItem `json:"subtitle,omitempty"`
	Video    []VideoStreamsVideoItem    `json:"video,omitempty"`
}

type VideoResume struct {
	Position *float64 `json:"position,omitempty"`
	Total    *float64 `json:"total,omitempty"`
}

type VideoDetailsBase struct {
	MediaDetailsBase               // embedded base type Media.Details.Base
	Art              *MediaArtwork `json:"art,omitempty"`
	Playcount        *int          `json:"playcount,omitempty"`
}

type VideoDetailsMedia struct {
	VideoDetailsBase         // embedded base type Video.Details.Base
	Title            *string `json:"title,omitempty"`
}

type VideoDetailsItem struct {
	VideoDetailsMedia         // embedded base type Video.Details.Media
	Dateadded         *string `json:"dateadded,omitempty"`
	File              *string `json:"file,omitempty"`
	Lastplayed        *string `json:"lastplayed,omitempty"`
	Plot              *string `json:"plot,omitempty"`
}

type VideoDetailsFile struct {
	VideoDetailsItem              // embedded base type Video.Details.Item
	Director         ArrayString  `json:"director,omitempty"`
	Resume           *VideoResume `json:"resume,omitempty"`
	// Runtime in seconds
	Runtime       *int          `json:"runtime,omitempty"`
	Streamdetails *VideoStreams `json:"streamdetails,omitempty"`
}

type VideoDetailsMovie struct {
	VideoDetailsFile                // embedded base type Video.Details.File
	Cast             VideoCast      `json:"cast,omitempty"`
	Country          ArrayString    `json:"country,omitempty"`
	Genre            ArrayString    `json:"genre,omitempty"`
	IMDbNumber       *string        `json:"imdbnumber,omitempty"`
	MovieID          LibraryID      `json:"movieid"`
	MPAA             *string        `json:"mpaa,omitempty"`
	Originaltitle    *string        `json:"originaltitle,omitempty"`
	Plotoutline      *string        `json:"plotoutline,omitempty"`
	Premiered        *string        `json:"premiered,omitempty"`
	Rating           *float64       `json:"rating,omitempty"`
	Ratings          *VideoRatings  `json:"ratings,omitempty"`
	Set              *string        `json:"set,omitempty"`
	SetID            *LibraryID     `json:"setid,omitempty"`
	Showlink         ArrayString    `json:"showlink,omitempty"`
	Sorttitle        *string        `json:"sorttitle,omitempty"`
	Studio           ArrayString    `json:"studio,omitempty"`
	Tag              ArrayString    `json:"tag,omitempty"`
	Tagline          *string        `json:"tagline,omitempty"`
	Top250           *int           `json:"top250,omitempty"`
	Trailer          *string        `json:"trailer,omitempty"`
	UniqueID         *MediaUniqueID `json:"uniqueid,omitempty"`
	Userrating       *int           `json:"userrating,omitempty"`
	Votes            *string        `json:"votes,omitempty"`
	Writer           ArrayString    `json:"writer,omitempty"`
	Year             *int           `json:"year,omitempty"`
}

type VideoDetailsMovieSet struct {
	VideoDetailsMedia           // embedded base type Video.Details.Media
	Plot              *string   `json:"plot,omitempty"`
	SetID             LibraryID `json:"setid"`
}

type VideoDetailsMovieSetExtended struct {
	VideoDetailsMovieSet                     // embedded base type Video.Details.MovieSet
	Limits               ListLimitsReturned  `json:"limits"`
	Movies               []VideoDetailsMovie `json:"movies,omitempty"`
}

type VideoDetailsTVShow struct {
	VideoDetailsItem               // embedded base type Video.Details.Item
	Cast             VideoCast     `json:"cast,omitempty"`
	Episode          *int          `json:"episode,omitempty"`
	Episodeguide     *string       `json:"episodeguide,omitempty"`
	Genre            ArrayString   `json:"genre,omitempty"`
	IMDbNumber       *string       `json:"imdbnumber,omitempty"`
	MPAA             *string       `json:"mpaa,omitempty"`
	Originaltitle    *string       `json:"originaltitle,omitempty"`
	Premiered        *string       `json:"premiered,omitempty"`
	Rating           *float64      `json:"rating,omitempty"`
	Ratings          *VideoRatings `json:"ratings,omitempty"`
	// Runtime in seconds
	Runtime   *int    `json:"runtime,omitempty"`
	Season    *int    `json:"season,omitempty"`
	Sorttitle *string `json:"sorttitle,omitempty"`
	// Returns 'returning series', 'in production', 'planned', 'cancelled' or 'ended'
	Status          *string        `json:"status,omitempty"`
	Studio          ArrayString    `json:"studio,omitempty"`
	Tag             ArrayString    `json:"tag,omitempty"`
	TVshowID        LibraryID      `json:"tvshowid"`
	UniqueID        *MediaUniqueID `json:"uniqueid,omitempty"`
	Userrating      *int           `json:"userrating,omitempty"`
	Votes           *string        `json:"votes,omitempty"`
	Watchedepisodes *int           `json:"watchedepisodes,omitempty"`
	Year            *int           `json:"year,omitempty"`
}

type VideoDetailsSeason struct {
	VideoDetailsBase            // embedded base type Video.Details.Base
	Episode          *int       `json:"episode,omitempty"`
	Season           int        `json:"season"`
	SeasonID         LibraryID  `json:"seasonid"`
	Showtitle        *string    `json:"showtitle,omitempty"`
	Title            *string    `json:"title,omitempty"`
	TVshowID         *LibraryID `json:"tvshowid,omitempty"`
	Userrating       *int       `json:"userrating,omitempty"`
	Watchedepisodes  *int       `json:"watchedepisodes,omitempty"`
}

type VideoDetailsEpisode struct {
	VideoDetailsFile                  // embedded base type Video.Details.File
	Cast               VideoCast      `json:"cast,omitempty"`
	Episode            *int           `json:"episode,omitempty"`
	EpisodeID          LibraryID      `json:"episodeid"`
	Firstaired         *string        `json:"firstaired,omitempty"`
	Originaltitle      *string        `json:"originaltitle,omitempty"`
	Productioncode     *string        `json:"productioncode,omitempty"`
	Rating             *float64       `json:"rating,omitempty"`
	Ratings            *VideoRatings  `json:"ratings,omitempty"`
	Season             *int           `json:"season,omitempty"`
	SeasonID           *LibraryID     `json:"seasonid,omitempty"`
	Showtitle          *string        `json:"showtitle,omitempty"`
	Specialsortepisode *int           `json:"specialsortepisode,omitempty"`
	Specialsortseason  *int           `json:"specialsortseason,omitempty"`
	TVshowID           *LibraryID     `json:"tvshowid,omitempty"`
	UniqueID           *MediaUniqueID `json:"uniqueid,omitempty"`
	Userrating         *int           `json:"userrating,omitempty"`
	Votes              *string        `json:"votes,omitempty"`
	Writer             ArrayString    `json:"writer,omitempty"`
}

type VideoDetailsMusicVideo struct {
	VideoDetailsFile             // embedded base type Video.Details.File
	Album            *string     `json:"album,omitempty"`
	Artist           ArrayString `json:"artist,omitempty"`
	Genre            ArrayString `json:"genre,omitempty"`
	MusicvideoID     LibraryID   `json:"musicvideoid"`
	Premiered        *string     `json:"premiered,omitempty"`
	Rating           *float64    `json:"rating,omitempty"`
	Studio           ArrayString `json:"studio,omitempty"`
	Tag              ArrayString `json:"tag,omitempty"`
	Track            *int        `json:"track,omitempty"`
	Userrating       *int        `json:"userrating,omitempty"`
	Year             *int        `json:"year,omitempty"`
}

type PVRPropertyName string

const (
	PVRPropertyNameAvailable PVRPropertyName = "available"
	PVRPropertyNameRecording PVRPropertyName = "recording"
	PVRPropertyNameScanning  PVRPropertyName = "scanning"
)

type PVRPropertyValue struct {
	Available *bool `json:"available,omitempty"`
	Recording *bool `json:"recording,omitempty"`
	Scanning  *bool `json:"scanning,omitempty"`
}

// PVRChannelGroupID is a union; decoded as any. See schema key "PVR.ChannelGroup.Id" in types.json.
type PVRChannelGroupID any

// Extends Item.Fields.Base.
type PVRFieldsBroadcast []string

type PVRDetailsBroadcast struct {
	ItemDetailsBase            // embedded base type Item.Details.Base
	BroadcastID     LibraryID  `json:"broadcastid"`
	Cast            *string    `json:"cast,omitempty"`
	ClientID        *LibraryID `json:"clientid,omitempty"`
	Director        *string    `json:"director,omitempty"`
	Endtime         *string    `json:"endtime,omitempty"`
	Episodename     *string    `json:"episodename,omitempty"`
	Episodenum      *int       `json:"episodenum,omitempty"`
	Episodepart     *int       `json:"episodepart,omitempty"`
	Firstaired      *string    `json:"firstaired,omitempty"`
	Genre           *string    `json:"genre,omitempty"`
	Hasrecording    *bool      `json:"hasrecording,omitempty"`
	Hasreminder     *bool      `json:"hasreminder,omitempty"`
	Hastimer        *bool      `json:"hastimer,omitempty"`
	Hastimerrule    *bool      `json:"hastimerrule,omitempty"`
	IMDbNumber      *int       `json:"imdbnumber,omitempty"`
	Isactive        *bool      `json:"isactive,omitempty"`
	// Deprecated - Use GetBroadcastIsPlayable instead
	Isplayable         *bool    `json:"isplayable,omitempty"`
	Isseries           *bool    `json:"isseries,omitempty"`
	Originaltitle      *string  `json:"originaltitle,omitempty"`
	Parentalrating     *int     `json:"parentalrating,omitempty"`
	Plot               *string  `json:"plot,omitempty"`
	Plotoutline        *string  `json:"plotoutline,omitempty"`
	Progress           *int     `json:"progress,omitempty"`
	Progresspercentage *float64 `json:"progresspercentage,omitempty"`
	Rating             *int     `json:"rating,omitempty"`
	Recording          *string  `json:"recording,omitempty"`
	Runtime            *int     `json:"runtime,omitempty"`
	Seasonnum          *int     `json:"seasonnum,omitempty"`
	Starttime          *string  `json:"starttime,omitempty"`
	Thumbnail          *string  `json:"thumbnail,omitempty"`
	Title              *string  `json:"title,omitempty"`
	Wasactive          *bool    `json:"wasactive,omitempty"`
	Writer             *string  `json:"writer,omitempty"`
	Year               *int     `json:"year,omitempty"`
}

// Extends Item.Fields.Base.
type PVRFieldsChannel []string

type PVRDetailsChannel struct {
	ItemDetailsBase                       // embedded base type Item.Details.Base
	Broadcastnext    *PVRDetailsBroadcast `json:"broadcastnext,omitempty"`
	Broadcastnow     *PVRDetailsBroadcast `json:"broadcastnow,omitempty"`
	Channel          *string              `json:"channel,omitempty"`
	ChannelID        LibraryID            `json:"channelid"`
	Channelnumber    *int                 `json:"channelnumber,omitempty"`
	Channeltype      *PVRChannelType      `json:"channeltype,omitempty"`
	ClientID         *LibraryID           `json:"clientid,omitempty"`
	Hasarchive       *bool                `json:"hasarchive,omitempty"`
	Hidden           *bool                `json:"hidden,omitempty"`
	Icon             *string              `json:"icon,omitempty"`
	Isrecording      *bool                `json:"isrecording,omitempty"`
	Lastplayed       *string              `json:"lastplayed,omitempty"`
	Locked           *bool                `json:"locked,omitempty"`
	Subchannelnumber *int                 `json:"subchannelnumber,omitempty"`
	Thumbnail        *string              `json:"thumbnail,omitempty"`
	UniqueID         int                  `json:"uniqueid"`
}

type PVRDetailsChannelGroup struct {
	ItemDetailsBase                // embedded base type Item.Details.Base
	ChannelgroupID  LibraryID      `json:"channelgroupid"`
	Channeltype     PVRChannelType `json:"channeltype"`
}

type PVRDetailsChannelGroupExtended struct {
	PVRDetailsChannelGroup                     // embedded base type PVR.Details.ChannelGroup
	Channels               []PVRDetailsChannel `json:"channels,omitempty"`
	Limits                 ListLimitsReturned  `json:"limits"`
}

// Extends Item.Fields.Base.
type PVRFieldsClient []string

type PVRDetailsClient struct {
	ItemDetailsBase                 // embedded base type Item.Details.Base
	AddonID               *string   `json:"addonid,omitempty"`
	ClientID              LibraryID `json:"clientid"`
	Supportschannelgroups *bool     `json:"supportschannelgroups,omitempty"`
	Supportschannelscan   *bool     `json:"supportschannelscan,omitempty"`
	Supportsepg           *bool     `json:"supportsepg,omitempty"`
	Supportsradio         *bool     `json:"supportsradio,omitempty"`
	Supportsrecordings    *bool     `json:"supportsrecordings,omitempty"`
	Supportstimers        *bool     `json:"supportstimers,omitempty"`
	Supportstv            *bool     `json:"supportstv,omitempty"`
}

type PVRTimerState string

const (
	PVRTimerStateUnknown       PVRTimerState = "unknown"
	PVRTimerStateNew           PVRTimerState = "new"
	PVRTimerStateScheduled     PVRTimerState = "scheduled"
	PVRTimerStateRecording     PVRTimerState = "recording"
	PVRTimerStateCompleted     PVRTimerState = "completed"
	PVRTimerStateAborted       PVRTimerState = "aborted"
	PVRTimerStateCancelled     PVRTimerState = "cancelled"
	PVRTimerStateConflictOk    PVRTimerState = "conflict_ok"
	PVRTimerStateConflictNotok PVRTimerState = "conflict_notok"
	PVRTimerStateError         PVRTimerState = "error"
	PVRTimerStateDisabled      PVRTimerState = "disabled"
)

// Extends Item.Fields.Base.
type PVRFieldsTimer []string

type PVRDetailsTimer struct {
	ItemDetailsBase                          // embedded base type Item.Details.Base
	BroadcastID              *LibraryID      `json:"broadcastid,omitempty"`
	ChannelID                *LibraryID      `json:"channelid,omitempty"`
	ClientID                 *LibraryID      `json:"clientid,omitempty"`
	Directory                *string         `json:"directory,omitempty"`
	Endanytime               *bool           `json:"endanytime,omitempty"`
	Endmargin                *int            `json:"endmargin,omitempty"`
	Endtime                  *string         `json:"endtime,omitempty"`
	Epgsearchstring          *string         `json:"epgsearchstring,omitempty"`
	EpgUID                   *int            `json:"epguid,omitempty"`
	File                     *string         `json:"file,omitempty"`
	Firstday                 *string         `json:"firstday,omitempty"`
	Fulltextepgsearch        *bool           `json:"fulltextepgsearch,omitempty"`
	Ismanual                 *bool           `json:"ismanual,omitempty"`
	Isradio                  *bool           `json:"isradio,omitempty"`
	Isreadonly               *bool           `json:"isreadonly,omitempty"`
	Isreminder               *bool           `json:"isreminder,omitempty"`
	Istimerrule              *bool           `json:"istimerrule,omitempty"`
	Lifetime                 *int            `json:"lifetime,omitempty"`
	Maxrecordings            *int            `json:"maxrecordings,omitempty"`
	Preventduplicateepisodes *int            `json:"preventduplicateepisodes,omitempty"`
	Priority                 *int            `json:"priority,omitempty"`
	Recordinggroup           *int            `json:"recordinggroup,omitempty"`
	Runtime                  *int            `json:"runtime,omitempty"`
	Startanytime             *bool           `json:"startanytime,omitempty"`
	Startmargin              *int            `json:"startmargin,omitempty"`
	Starttime                *string         `json:"starttime,omitempty"`
	State                    *PVRTimerState  `json:"state,omitempty"`
	Summary                  *string         `json:"summary,omitempty"`
	TimerID                  LibraryID       `json:"timerid"`
	Title                    *string         `json:"title,omitempty"`
	Weekdays                 []GlobalWeekday `json:"weekdays,omitempty"`
}

// Extends Item.Fields.Base.
type PVRFieldsRecording []string

type PVRDetailsRecording struct {
	ItemDetailsBase               // embedded base type Item.Details.Base
	Art             *MediaArtwork `json:"art,omitempty"`
	Channel         *string       `json:"channel,omitempty"`
	ChannelUID      *int          `json:"channeluid,omitempty"`
	ClientID        *LibraryID    `json:"clientid,omitempty"`
	Directory       *string       `json:"directory,omitempty"`
	Endtime         *string       `json:"endtime,omitempty"`
	EpgeventID      *int          `json:"epgeventid,omitempty"`
	Episode         *int          `json:"episode,omitempty"`
	File            *string       `json:"file,omitempty"`
	Genre           *string       `json:"genre,omitempty"`
	Icon            *string       `json:"icon,omitempty"`
	Isdeleted       *bool         `json:"isdeleted,omitempty"`
	Lifetime        *int          `json:"lifetime,omitempty"`
	Playcount       *int          `json:"playcount,omitempty"`
	Plot            *string       `json:"plot,omitempty"`
	Plotoutline     *string       `json:"plotoutline,omitempty"`
	Radio           *bool         `json:"radio,omitempty"`
	RecordingID     LibraryID     `json:"recordingid"`
	Resume          *VideoResume  `json:"resume,omitempty"`
	Runtime         *int          `json:"runtime,omitempty"`
	Season          *int          `json:"season,omitempty"`
	Showtitle       *string       `json:"showtitle,omitempty"`
	Starttime       *string       `json:"starttime,omitempty"`
	StreamURL       *string       `json:"streamurl,omitempty"`
	Title           *string       `json:"title,omitempty"`
}

type TexturesDetailsSize struct {
	// Height of texture
	Height *int `json:"height,omitempty"`
	// Date of last use
	Lastused *string `json:"lastused,omitempty"`
	// Size of the texture (1 == largest)
	Size *int `json:"size,omitempty"`
	// Number of uses
	Usecount *int `json:"usecount,omitempty"`
	// Width of texture
	Width *int `json:"width,omitempty"`
}

// Extends Item.Fields.Base.
type TexturesFieldsTexture []string

type TexturesDetailsTexture struct {
	// Cached URL on disk
	CachedURL *string `json:"cachedurl,omitempty"`
	// Hash of image
	Imagehash *string `json:"imagehash,omitempty"`
	// Last time source was checked for changes
	Lasthashcheck *string               `json:"lasthashcheck,omitempty"`
	Sizes         []TexturesDetailsSize `json:"sizes,omitempty"`
	TextureID     *LibraryID            `json:"textureid,omitempty"`
	// Original source URL
	URL *string `json:"url,omitempty"`
}

type ProfilesPassword struct {
	// Password Encryption
	// Default: md5.
	Encryption *string `json:"encryption,omitempty"`
	// Password
	Value string `json:"value"`
}

// Extends Item.Fields.Base.
type ProfilesFieldsProfile []string

type ProfilesDetailsProfile struct {
	ItemDetailsBase         // embedded base type Item.Details.Base
	Lockmode        *int    `json:"lockmode,omitempty"`
	Thumbnail       *string `json:"thumbnail,omitempty"`
}

type ListFilterRule struct {
	Operator ListFilterOperators `json:"operator"`
	Value    any                 `json:"value"`
}

type ListFilterRuleMovies struct {
	ListFilterRule                        // embedded base type List.Filter.Rule
	Field          ListFilterFieldsMovies `json:"field"`
}

type ListFilterRuleTVShows struct {
	ListFilterRule                         // embedded base type List.Filter.Rule
	Field          ListFilterFieldsTVShows `json:"field"`
}

type ListFilterRuleEpisodes struct {
	ListFilterRule                          // embedded base type List.Filter.Rule
	Field          ListFilterFieldsEpisodes `json:"field"`
}

type ListFilterRuleMusicVideos struct {
	ListFilterRule                             // embedded base type List.Filter.Rule
	Field          ListFilterFieldsMusicVideos `json:"field"`
}

type ListFilterRuleArtists struct {
	ListFilterRule                         // embedded base type List.Filter.Rule
	Field          ListFilterFieldsArtists `json:"field"`
}

type ListFilterRuleAlbums struct {
	ListFilterRule                        // embedded base type List.Filter.Rule
	Field          ListFilterFieldsAlbums `json:"field"`
}

type ListFilterRuleSongs struct {
	ListFilterRule                       // embedded base type List.Filter.Rule
	Field          ListFilterFieldsSongs `json:"field"`
}

type ListFilterRuleTextures struct {
	ListFilterRule                          // embedded base type List.Filter.Rule
	Field          ListFilterFieldsTextures `json:"field"`
}

// ListFilterMovies is a union; decoded as any. See schema key "List.Filter.Movies" in types.json.
type ListFilterMovies any

// ListFilterTVShows is a union; decoded as any. See schema key "List.Filter.TVShows" in types.json.
type ListFilterTVShows any

// ListFilterEpisodes is a union; decoded as any. See schema key "List.Filter.Episodes" in types.json.
type ListFilterEpisodes any

// ListFilterMusicVideos is a union; decoded as any. See schema key "List.Filter.MusicVideos" in types.json.
type ListFilterMusicVideos any

// ListFilterArtists is a union; decoded as any. See schema key "List.Filter.Artists" in types.json.
type ListFilterArtists any

// ListFilterAlbums is a union; decoded as any. See schema key "List.Filter.Albums" in types.json.
type ListFilterAlbums any

// ListFilterSongs is a union; decoded as any. See schema key "List.Filter.Songs" in types.json.
type ListFilterSongs any

// ListFilterTextures is a union; decoded as any. See schema key "List.Filter.Textures" in types.json.
type ListFilterTextures any

type ListItemBase struct {
	Album            *string                `json:"album,omitempty"`
	Albumartist      ArrayString            `json:"albumartist,omitempty"`
	AlbumartistID    ArrayInteger           `json:"albumartistid,omitempty"`
	AlbumID          *LibraryID             `json:"albumid,omitempty"`
	Albumlabel       *string                `json:"albumlabel,omitempty"`
	Albumreleasetype *AudioAlbumReleaseType `json:"albumreleasetype,omitempty"`
	Albumstatus      *string                `json:"albumstatus,omitempty"`
	Bitrate          *int                   `json:"bitrate,omitempty"`
	Bpm              *int                   `json:"bpm,omitempty"`
	Cast             VideoCast              `json:"cast,omitempty"`
	Channels         *int                   `json:"channels,omitempty"`
	Comment          *string                `json:"comment,omitempty"`
	Compilation      *bool                  `json:"compilation,omitempty"`
	Contributors     AudioContributors      `json:"contributors,omitempty"`
	Country          ArrayString            `json:"country,omitempty"`
	Customproperties *ItemCustomProperties  `json:"customproperties,omitempty"`
	Description      *string                `json:"description,omitempty"`
	Disc             *int                   `json:"disc,omitempty"`
	Disctitle        *string                `json:"disctitle,omitempty"`
	Displaycomposer  *string                `json:"displaycomposer,omitempty"`
	Displayconductor *string                `json:"displayconductor,omitempty"`
	Displaylyricist  *string                `json:"displaylyricist,omitempty"`
	Displayorchestra *string                `json:"displayorchestra,omitempty"`
	Duration         *int                   `json:"duration,omitempty"`
	// An experimental property for debug purposes, often same as mediapath but when different gives the actual file playing that should also be in file property
	Dynpath      *string    `json:"dynpath,omitempty"`
	Episode      *int       `json:"episode,omitempty"`
	Episodeguide *string    `json:"episodeguide,omitempty"`
	Firstaired   *string    `json:"firstaired,omitempty"`
	ID           *LibraryID `json:"id,omitempty"`
	IMDbNumber   *string    `json:"imdbnumber,omitempty"`
	Isboxset     *bool      `json:"isboxset,omitempty"`
	Lyrics       *string    `json:"lyrics,omitempty"`
	// Media source path that identifies the item
	Mediapath           *string                `json:"mediapath,omitempty"`
	Mood                ArrayString            `json:"mood,omitempty"`
	MPAA                *string                `json:"mpaa,omitempty"`
	MusicbrainzartistID ArrayString            `json:"musicbrainzartistid,omitempty"`
	MusicbrainztrackID  *string                `json:"musicbrainztrackid,omitempty"`
	Originaldate        *string                `json:"originaldate,omitempty"`
	Originaltitle       *string                `json:"originaltitle,omitempty"`
	Plotoutline         *string                `json:"plotoutline,omitempty"`
	Premiered           *string                `json:"premiered,omitempty"`
	Productioncode      *string                `json:"productioncode,omitempty"`
	Releasedate         *string                `json:"releasedate,omitempty"`
	Releasetype         *AudioAlbumReleaseType `json:"releasetype,omitempty"`
	Samplerate          *int                   `json:"samplerate,omitempty"`
	Season              *int                   `json:"season,omitempty"`
	Set                 *string                `json:"set,omitempty"`
	SetID               *LibraryID             `json:"setid,omitempty"`
	Showlink            ArrayString            `json:"showlink,omitempty"`
	Showtitle           *string                `json:"showtitle,omitempty"`
	Sorttitle           *string                `json:"sorttitle,omitempty"`
	Specialsortepisode  *int                   `json:"specialsortepisode,omitempty"`
	Specialsortseason   *int                   `json:"specialsortseason,omitempty"`
	Studio              ArrayString            `json:"studio,omitempty"`
	Style               ArrayString            `json:"style,omitempty"`
	Tag                 ArrayString            `json:"tag,omitempty"`
	Tagline             *string                `json:"tagline,omitempty"`
	Theme               ArrayString            `json:"theme,omitempty"`
	Top250              *int                   `json:"top250,omitempty"`
	Totaldiscs          *int                   `json:"totaldiscs,omitempty"`
	Track               *int                   `json:"track,omitempty"`
	Trailer             *string                `json:"trailer,omitempty"`
	TVshowID            *LibraryID             `json:"tvshowid,omitempty"`
	Type                *string                `json:"type,omitempty"`
	UniqueID            *MediaUniqueID         `json:"uniqueid,omitempty"`
	Votes               *string                `json:"votes,omitempty"`
	Watchedepisodes     *int                   `json:"watchedepisodes,omitempty"`
	Writer              ArrayString            `json:"writer,omitempty"`
}

// Extends Item.Fields.Base.
type ListFieldsAll []string

type ListItemAll struct {
	ListItemBase                     // embedded base type List.Item.Base
	Channel          *string         `json:"channel,omitempty"`
	Channelnumber    *int            `json:"channelnumber,omitempty"`
	Channeltype      *PVRChannelType `json:"channeltype,omitempty"`
	Endtime          *string         `json:"endtime,omitempty"`
	Hidden           *bool           `json:"hidden,omitempty"`
	Locked           *bool           `json:"locked,omitempty"`
	Starttime        *string         `json:"starttime,omitempty"`
	Subchannelnumber *int            `json:"subchannelnumber,omitempty"`
}

// Extends Item.Fields.Base.
type ListFieldsFiles []string

type ListItemFile struct {
	ListItemBase         // embedded base type List.Item.Base
	File         string  `json:"file"`
	Filetype     string  `json:"filetype"`
	Lastmodified *string `json:"lastmodified,omitempty"`
	Mimetype     *string `json:"mimetype,omitempty"`
	// Size of the file in bytes
	Size *int `json:"size,omitempty"`
}

type ListItemsSources []ListItemsSourcesItem

type AddonContent string

const (
	AddonContentUnknown    AddonContent = "unknown"
	AddonContentVideo      AddonContent = "video"
	AddonContentAudio      AddonContent = "audio"
	AddonContentImage      AddonContent = "image"
	AddonContentExecutable AddonContent = "executable"
)

// Extends Item.Fields.Base.
type AddonFields []string

type AddonDetails struct {
	ItemDetailsBase                                // embedded base type Item.Details.Base
	AddonID         string                         `json:"addonid"`
	Author          *string                        `json:"author,omitempty"`
	Broken          any                            `json:"broken,omitempty"`
	Dependencies    []AddonDetailsDependenciesItem `json:"dependencies,omitempty"`
	Deprecated      any                            `json:"deprecated,omitempty"`
	Description     *string                        `json:"description,omitempty"`
	Disclaimer      *string                        `json:"disclaimer,omitempty"`
	Enabled         *bool                          `json:"enabled,omitempty"`
	Extrainfo       []AddonDetailsExtrainfoItem    `json:"extrainfo,omitempty"`
	Fanart          *string                        `json:"fanart,omitempty"`
	Installed       *bool                          `json:"installed,omitempty"`
	Name            *string                        `json:"name,omitempty"`
	Path            *string                        `json:"path,omitempty"`
	Rating          *int                           `json:"rating,omitempty"`
	Summary         *string                        `json:"summary,omitempty"`
	Thumbnail       *string                        `json:"thumbnail,omitempty"`
	Type            AddonTypes                     `json:"type"`
	Version         *string                        `json:"version,omitempty"`
}

type GUIStereoscopyMode struct {
	Label string `json:"label"`
	Mode  string `json:"mode"`
}

type GUIPropertyName string

const (
	GUIPropertyNameCurrentwindow    GUIPropertyName = "currentwindow"
	GUIPropertyNameCurrentcontrol   GUIPropertyName = "currentcontrol"
	GUIPropertyNameSkin             GUIPropertyName = "skin"
	GUIPropertyNameFullscreen       GUIPropertyName = "fullscreen"
	GUIPropertyNameStereoscopicmode GUIPropertyName = "stereoscopicmode"
)

type GUIPropertyValue struct {
	Currentcontrol   *GUIPropertyValueCurrentcontrol `json:"currentcontrol,omitempty"`
	Currentwindow    *GUIPropertyValueCurrentwindow  `json:"currentwindow,omitempty"`
	Fullscreen       *bool                           `json:"fullscreen,omitempty"`
	Skin             *GUIPropertyValueSkin           `json:"skin,omitempty"`
	Stereoscopicmode *GUIStereoscopyMode             `json:"stereoscopicmode,omitempty"`
}

type SystemPropertyName string

const (
	SystemPropertyNameCanshutdown  SystemPropertyName = "canshutdown"
	SystemPropertyNameCansuspend   SystemPropertyName = "cansuspend"
	SystemPropertyNameCanhibernate SystemPropertyName = "canhibernate"
	SystemPropertyNameCanreboot    SystemPropertyName = "canreboot"
)

type SystemPropertyValue struct {
	Canhibernate *bool `json:"canhibernate,omitempty"`
	Canreboot    *bool `json:"canreboot,omitempty"`
	Canshutdown  *bool `json:"canshutdown,omitempty"`
	Cansuspend   *bool `json:"cansuspend,omitempty"`
}

type ApplicationPropertyName string

const (
	ApplicationPropertyNameVolume     ApplicationPropertyName = "volume"
	ApplicationPropertyNameMuted      ApplicationPropertyName = "muted"
	ApplicationPropertyNameName       ApplicationPropertyName = "name"
	ApplicationPropertyNameVersion    ApplicationPropertyName = "version"
	ApplicationPropertyNameVolume2    ApplicationPropertyName = "volume"
	ApplicationPropertyNameSorttokens ApplicationPropertyName = "sorttokens"
	ApplicationPropertyNameLanguage   ApplicationPropertyName = "language"
)

type ApplicationPropertyValue struct {
	// Current language code and region e.g. en_GB
	Language *string `json:"language,omitempty"`
	Muted    *bool   `json:"muted,omitempty"`
	Name     *string `json:"name,omitempty"`
	// Articles ignored during sorting when ignorearticle is enabled.
	Sorttokens ArrayString                      `json:"sorttokens,omitempty"`
	Version    *ApplicationPropertyValueVersion `json:"version,omitempty"`
	Volume     *int                             `json:"volume,omitempty"`
}

// Extends Item.Fields.Base.
type FavouriteFieldsFavourite []string

type FavouriteType string

const (
	FavouriteTypeMedia      FavouriteType = "media"
	FavouriteTypeWindow     FavouriteType = "window"
	FavouriteTypeScript     FavouriteType = "script"
	FavouriteTypeAndroidapp FavouriteType = "androidapp"
	FavouriteTypeUnknown    FavouriteType = "unknown"
)

type FavouriteDetailsFavourite struct {
	Path            *string       `json:"path,omitempty"`
	Thumbnail       *string       `json:"thumbnail,omitempty"`
	Title           string        `json:"title"`
	Type            FavouriteType `json:"type"`
	Window          *string       `json:"window,omitempty"`
	Windowparameter *string       `json:"windowparameter,omitempty"`
}

type SettingType string

const (
	SettingTypeBoolean SettingType = "boolean"
	SettingTypeInteger SettingType = "integer"
	SettingTypeNumber  SettingType = "number"
	SettingTypeString  SettingType = "string"
	SettingTypeAction  SettingType = "action"
	SettingTypeList    SettingType = "list"
	SettingTypePath    SettingType = "path"
	SettingTypeAddon   SettingType = "addon"
	SettingTypeDate    SettingType = "date"
	SettingTypeTime    SettingType = "time"
)

type SettingLevel string

const (
	SettingLevelBasic    SettingLevel = "basic"
	SettingLevelStandard SettingLevel = "standard"
	SettingLevelAdvanced SettingLevel = "advanced"
	SettingLevelExpert   SettingLevel = "expert"
)

// SettingValue is a union; decoded as any. See schema key "Setting.Value" in types.json.
type SettingValue any

type SettingValueList []SettingValue

// SettingValueExtended is a union; decoded as any. See schema key "Setting.Value.Extended" in types.json.
type SettingValueExtended any

type SettingDetailsControlBase struct {
	Delayed bool   `json:"delayed"`
	Format  string `json:"format"`
	Type    string `json:"type"`
}

type SettingDetailsControlCheckmark struct {
	SettingDetailsControlBase        // embedded base type Setting.Details.ControlBase
	Format                    string `json:"format"`
	Type                      string `json:"type"`
}

type SettingDetailsControlSpinner struct {
	SettingDetailsControlBase         // embedded base type Setting.Details.ControlBase
	Formatlabel               *string `json:"formatlabel,omitempty"`
	Minimumlabel              *string `json:"minimumlabel,omitempty"`
	Type                      string  `json:"type"`
}

type SettingDetailsControlHeading struct {
	SettingDetailsControlBase         // embedded base type Setting.Details.ControlBase
	Heading                   *string `json:"heading,omitempty"`
}

type SettingDetailsControlEdit struct {
	SettingDetailsControlHeading        // embedded base type Setting.Details.ControlHeading
	Hidden                       bool   `json:"hidden"`
	Type                         string `json:"type"`
	Verifynewvalue               bool   `json:"verifynewvalue"`
}

type SettingDetailsControlButton struct {
	SettingDetailsControlHeading        // embedded base type Setting.Details.ControlHeading
	Type                         string `json:"type"`
}

type SettingDetailsControlList struct {
	SettingDetailsControlHeading        // embedded base type Setting.Details.ControlHeading
	Multiselect                  bool   `json:"multiselect"`
	Type                         string `json:"type"`
}

type SettingDetailsControlSlider struct {
	SettingDetailsControlHeading        // embedded base type Setting.Details.ControlHeading
	Formatlabel                  string `json:"formatlabel"`
	Popup                        bool   `json:"popup"`
	Type                         string `json:"type"`
}

type SettingDetailsControlRange struct {
	SettingDetailsControlBase        // embedded base type Setting.Details.ControlBase
	Formatlabel               string `json:"formatlabel"`
	Formatvalue               string `json:"formatvalue"`
	Type                      string `json:"type"`
}

type SettingDetailsControlLabel struct {
	SettingDetailsControlBase        // embedded base type Setting.Details.ControlBase
	Format                    string `json:"format"`
	Type                      string `json:"type"`
}

// SettingDetailsControl is a union; decoded as any. See schema key "Setting.Details.Control" in types.json.
type SettingDetailsControl any

type SettingDetailsBase struct {
	Help  *string `json:"help,omitempty"`
	ID    string  `json:"id"`
	Label string  `json:"label"`
}

type SettingDetailsSettingBase struct {
	SettingDetailsBase                       // embedded base type Setting.Details.Base
	Control            SettingDetailsControl `json:"control,omitempty"`
	Enabled            bool                  `json:"enabled"`
	Level              SettingLevel          `json:"level"`
	Parent             *string               `json:"parent,omitempty"`
	Type               SettingType           `json:"type"`
}

type SettingDetailsSettingBool struct {
	SettingDetailsSettingBase      // embedded base type Setting.Details.SettingBase
	Default                   bool `json:"default"`
	Value                     bool `json:"value"`
}

type SettingDetailsSettingInt struct {
	SettingDetailsSettingBase                                       // embedded base type Setting.Details.SettingBase
	Default                   int                                   `json:"default"`
	Maximum                   *int                                  `json:"maximum,omitempty"`
	Minimum                   *int                                  `json:"minimum,omitempty"`
	Options                   []SettingDetailsSettingIntOptionsItem `json:"options,omitempty"`
	Step                      *int                                  `json:"step,omitempty"`
	Value                     int                                   `json:"value"`
}

type SettingDetailsSettingNumber struct {
	SettingDetailsSettingBase         // embedded base type Setting.Details.SettingBase
	Default                   float64 `json:"default"`
	Maximum                   float64 `json:"maximum"`
	Minimum                   float64 `json:"minimum"`
	Step                      float64 `json:"step"`
	Value                     float64 `json:"value"`
}

type SettingDetailsSettingString struct {
	SettingDetailsSettingBase                                          // embedded base type Setting.Details.SettingBase
	Allowempty                bool                                     `json:"allowempty"`
	Default                   string                                   `json:"default"`
	Options                   []SettingDetailsSettingStringOptionsItem `json:"options,omitempty"`
	Value                     string                                   `json:"value"`
}

type SettingDetailsSettingAction struct {
	SettingDetailsSettingBase        // embedded base type Setting.Details.SettingBase
	Data                      string `json:"data"`
}

type SettingDetailsSettingList struct {
	SettingDetailsSettingBase                       // embedded base type Setting.Details.SettingBase
	Default                   SettingValueList      `json:"default"`
	Definition                SettingDetailsSetting `json:"definition"`
	Delimiter                 string                `json:"delimiter"`
	Elementtype               SettingType           `json:"elementtype"`
	MaximumItems              *int                  `json:"maximumItems,omitempty"`
	MinimumItems              *int                  `json:"minimumItems,omitempty"`
	Value                     SettingValueList      `json:"value"`
}

type SettingDetailsSettingPath struct {
	SettingDetailsSettingString          // embedded base type Setting.Details.SettingString
	Sources                     []string `json:"sources,omitempty"`
	Writable                    bool     `json:"writable"`
}

type SettingDetailsSettingAddon struct {
	SettingDetailsSettingString            // embedded base type Setting.Details.SettingString
	Addontype                   AddonTypes `json:"addontype"`
}

// Extends Setting.Details.SettingString.
type SettingDetailsSettingDate = SettingDetailsSettingString

// Extends Setting.Details.SettingString.
type SettingDetailsSettingTime = SettingDetailsSettingString

// SettingDetailsSetting is a union; decoded as any. See schema key "Setting.Details.Setting" in types.json.
type SettingDetailsSetting any

type SettingDetailsGroup struct {
	ID       string                  `json:"id"`
	Settings []SettingDetailsSetting `json:"settings,omitempty"`
}

type SettingDetailsCategory struct {
	SettingDetailsBase                       // embedded base type Setting.Details.Base
	Groups             []SettingDetailsGroup `json:"groups,omitempty"`
}

type SettingDetailsSection struct {
	SettingDetailsBase                          // embedded base type Setting.Details.Base
	Categories         []SettingDetailsCategory `json:"categories,omitempty"`
}

type VideoStreamsAudioItem struct {
	Channels *int    `json:"channels,omitempty"`
	Codec    *string `json:"codec,omitempty"`
	Language *string `json:"language,omitempty"`
}

type VideoStreamsSubtitleItem struct {
	Language *string `json:"language,omitempty"`
}

type VideoStreamsVideoItem struct {
	Aspect   *float64 `json:"aspect,omitempty"`
	Codec    *string  `json:"codec,omitempty"`
	Duration *int     `json:"duration,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Width    *int     `json:"width,omitempty"`
}

type ListItemsSourcesItem struct {
	ItemDetailsBase        // embedded base type Item.Details.Base
	File            string `json:"file"`
}

type AddonDetailsDependenciesItem struct {
	AddonID  string `json:"addonid"`
	Optional bool   `json:"optional"`
	Version  string `json:"version"`
}

type AddonDetailsExtrainfoItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type GUIPropertyValueCurrentcontrol struct {
	Label string `json:"label"`
}

type GUIPropertyValueCurrentwindow struct {
	ID    int    `json:"id"`
	Label string `json:"label"`
}

type GUIPropertyValueSkin struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

type ApplicationPropertyValueVersion struct {
	Major      int     `json:"major"`
	Minor      int     `json:"minor"`
	Revision   any     `json:"revision,omitempty"`
	Tag        string  `json:"tag"`
	Tagversion *string `json:"tagversion,omitempty"`
}

type SettingDetailsSettingIntOptionsItem struct {
	Label string `json:"label"`
	Value int    `json:"value"`
}

type SettingDetailsSettingStringOptionsItem struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// Unresolved references (not present in schema/types.json).
// AddonTypes is a fallback for the unresolved $ref "Addon.Types".
type AddonTypes string

// ListFilterFieldsAlbums is a fallback for the unresolved $ref "List.Filter.Fields.Albums".
type ListFilterFieldsAlbums string

// ListFilterFieldsArtists is a fallback for the unresolved $ref "List.Filter.Fields.Artists".
type ListFilterFieldsArtists string

// ListFilterFieldsEpisodes is a fallback for the unresolved $ref "List.Filter.Fields.Episodes".
type ListFilterFieldsEpisodes string

// ListFilterFieldsMovies is a fallback for the unresolved $ref "List.Filter.Fields.Movies".
type ListFilterFieldsMovies string

// ListFilterFieldsMusicVideos is a fallback for the unresolved $ref "List.Filter.Fields.MusicVideos".
type ListFilterFieldsMusicVideos string

// ListFilterFieldsSongs is a fallback for the unresolved $ref "List.Filter.Fields.Songs".
type ListFilterFieldsSongs string

// ListFilterFieldsTVShows is a fallback for the unresolved $ref "List.Filter.Fields.TVShows".
type ListFilterFieldsTVShows string

// ListFilterFieldsTextures is a fallback for the unresolved $ref "List.Filter.Fields.Textures".
type ListFilterFieldsTextures string

// ListFilterOperators is a fallback for the unresolved $ref "List.Filter.Operators".
type ListFilterOperators string
