// Code generated by cmd/kodi-gen from schema/v13/notifications.json. DO NOT EDIT.

package v13

// Schema version 13.5.0.

// Notification names.
const (
	NotificationPlayerOnPlay                = "Player.OnPlay"
	NotificationPlayerOnResume              = "Player.OnResume"
	NotificationPlayerOnAVStart             = "Player.OnAVStart"
	NotificationPlayerOnAVChange            = "Player.OnAVChange"
	NotificationPlayerOnPause               = "Player.OnPause"
	NotificationPlayerOnStop                = "Player.OnStop"
	NotificationPlayerOnSpeedChanged        = "Player.OnSpeedChanged"
	NotificationPlayerOnSeek                = "Player.OnSeek"
	NotificationPlayerOnPropertyChanged     = "Player.OnPropertyChanged"
	NotificationPlaylistOnAdd               = "Playlist.OnAdd"
	NotificationPlaylistOnRemove            = "Playlist.OnRemove"
	NotificationPlaylistOnClear             = "Playlist.OnClear"
	NotificationAudioLibraryOnUpdate        = "AudioLibrary.OnUpdate"
	NotificationAudioLibraryOnRemove        = "AudioLibrary.OnRemove"
	NotificationAudioLibraryOnScanStarted   = "AudioLibrary.OnScanStarted"
	NotificationAudioLibraryOnScanFinished  = "AudioLibrary.OnScanFinished"
	NotificationAudioLibraryOnCleanStarted  = "AudioLibrary.OnCleanStarted"
	NotificationAudioLibraryOnCleanFinished = "AudioLibrary.OnCleanFinished"
	NotificationAudioLibraryOnExport        = "AudioLibrary.OnExport"
	NotificationVideoLibraryOnUpdate        = "VideoLibrary.OnUpdate"
	NotificationVideoLibraryOnExport        = "VideoLibrary.OnExport"
	NotificationVideoLibraryOnRemove        = "VideoLibrary.OnRemove"
	NotificationVideoLibraryOnScanStarted   = "VideoLibrary.OnScanStarted"
	NotificationVideoLibraryOnScanFinished  = "VideoLibrary.OnScanFinished"
	NotificationVideoLibraryOnCleanStarted  = "VideoLibrary.OnCleanStarted"
	NotificationVideoLibraryOnCleanFinished = "VideoLibrary.OnCleanFinished"
	NotificationVideoLibraryOnRefresh       = "VideoLibrary.OnRefresh"
	NotificationSystemOnQuit                = "System.OnQuit"
	NotificationSystemOnRestart             = "System.OnRestart"
	NotificationSystemOnSleep               = "System.OnSleep"
	NotificationSystemOnWake                = "System.OnWake"
	NotificationSystemOnLowBattery          = "System.OnLowBattery"
	NotificationApplicationOnVolumeChanged  = "Application.OnVolumeChanged"
	NotificationInputOnInputRequested       = "Input.OnInputRequested"
	NotificationInputOnInputFinished        = "Input.OnInputFinished"
	NotificationGUIOnScreensaverActivated   = "GUI.OnScreensaverActivated"
	NotificationGUIOnScreensaverDeactivated = "GUI.OnScreensaverDeactivated"
	NotificationGUIOnDPMSActivated          = "GUI.OnDPMSActivated"
	NotificationGUIOnDPMSDeactivated        = "GUI.OnDPMSDeactivated"
)

// Playback of a media item has been started or the playback speed has changed. If there is no ID available extra information will be provided.
// Player.OnPlay.
// PlayerOnPlayData carries the data of Player.OnPlay.
type PlayerOnPlayData = PlayerNotificationsData

// PlayerOnPlayHandler handles Player.OnPlay notifications.
type PlayerOnPlayHandler func(sender string, data PlayerOnPlayData)

// Playback of a media item has been resumed. If there is no ID available extra information will be provided.
// Player.OnResume.
// PlayerOnResumeData carries the data of Player.OnResume.
type PlayerOnResumeData = PlayerNotificationsData

// PlayerOnResumeHandler handles Player.OnResume notifications.
type PlayerOnResumeHandler func(sender string, data PlayerOnResumeData)

// Playback of a media item has been started and first frame is available. If there is no ID available extra information will be provided.
// Player.OnAVStart.
// PlayerOnAVStartData carries the data of Player.OnAVStart.
type PlayerOnAVStartData = PlayerNotificationsData

// PlayerOnAVStartHandler handles Player.OnAVStart notifications.
type PlayerOnAVStartHandler func(sender string, data PlayerOnAVStartData)

// Audio- or videostream has changed. If there is no ID available extra information will be provided.
// Player.OnAVChange.
// PlayerOnAVChangeData carries the data of Player.OnAVChange.
type PlayerOnAVChangeData = PlayerNotificationsData

// PlayerOnAVChangeHandler handles Player.OnAVChange notifications.
type PlayerOnAVChangeHandler func(sender string, data PlayerOnAVChangeData)

// Playback of a media item has been paused. If there is no ID available extra information will be provided.
// Player.OnPause.
// PlayerOnPauseData carries the data of Player.OnPause.
type PlayerOnPauseData = PlayerNotificationsData

// PlayerOnPauseHandler handles Player.OnPause notifications.
type PlayerOnPauseHandler func(sender string, data PlayerOnPauseData)

// Playback of a media item has been stopped. If there is no ID available extra information will be provided.
// Player.OnStop.
// Data for Player.OnStop.
type PlayerOnStopData struct {
	// Whether the player has reached the end of the playable item(s) or not
	End  bool              `json:"end"`
	Item NotificationsItem `json:"item,omitempty"`
}

// PlayerOnStopHandler handles Player.OnStop notifications.
type PlayerOnStopHandler func(sender string, data PlayerOnStopData)

// Speed of the playback of a media item has been changed. If there is no ID available extra information will be provided.
// Player.OnSpeedChanged.
// PlayerOnSpeedChangedData carries the data of Player.OnSpeedChanged.
type PlayerOnSpeedChangedData = PlayerNotificationsData

// PlayerOnSpeedChangedHandler handles Player.OnSpeedChanged notifications.
type PlayerOnSpeedChangedHandler func(sender string, data PlayerOnSpeedChangedData)

// The playback position has been changed. If there is no ID available extra information will be provided.
// Player.OnSeek.
// Data for Player.OnSeek.
type PlayerOnSeekData struct {
	Item   NotificationsItem             `json:"item,omitempty"`
	Player PlayerNotificationsPlayerSeek `json:"player"`
}

// PlayerOnSeekHandler handles Player.OnSeek notifications.
type PlayerOnSeekHandler func(sender string, data PlayerOnSeekData)

// A property of the playing items has changed.
// Player.OnPropertyChanged.
// Data for Player.OnPropertyChanged.
type PlayerOnPropertyChangedData struct {
	Player   PlayerNotificationsPlayer `json:"player"`
	Property *PlayerPropertyValue      `json:"property,omitempty"`
}

// PlayerOnPropertyChangedHandler handles Player.OnPropertyChanged notifications.
type PlayerOnPropertyChangedHandler func(sender string, data PlayerOnPropertyChangedData)

// A playlist item has been added.
// Playlist.OnAdd.
// Data for Playlist.OnAdd.
type PlaylistOnAddData struct {
	Item       NotificationsItem `json:"item,omitempty"`
	PlaylistID PlaylistID        `json:"playlistid"`
	Position   *PlaylistPosition `json:"position,omitempty"`
}

// PlaylistOnAddHandler handles Playlist.OnAdd notifications.
type PlaylistOnAddHandler func(sender string, data PlaylistOnAddData)

// A playlist item has been removed.
// Playlist.OnRemove.
// Data for Playlist.OnRemove.
type PlaylistOnRemoveData struct {
	PlaylistID PlaylistID        `json:"playlistid"`
	Position   *PlaylistPosition `json:"position,omitempty"`
}

// PlaylistOnRemoveHandler handles Playlist.OnRemove notifications.
type PlaylistOnRemoveHandler func(sender string, data PlaylistOnRemoveData)

// A playlist item has been cleared.
// Playlist.OnClear.
// Data for Playlist.OnClear.
type PlaylistOnClearData struct {
	PlaylistID PlaylistID `json:"playlistid"`
}

// PlaylistOnClearHandler handles Playlist.OnClear notifications.
type PlaylistOnClearHandler func(sender string, data PlaylistOnClearData)

// An audio item has been updated.
// AudioLibrary.OnUpdate.
// Data for AudioLibrary.OnUpdate.
type AudioLibraryOnUpdateData struct {
	// True if the update is for a newly added item.
	Added *OptionalBoolean `json:"added,omitempty"`
	ID    LibraryID        `json:"id"`
	// True if the update is being performed within a transaction.
	Transaction *OptionalBoolean `json:"transaction,omitempty"`
	Type        string           `json:"type"`
}

// AudioLibraryOnUpdateHandler handles AudioLibrary.OnUpdate notifications.
type AudioLibraryOnUpdateHandler func(sender string, data AudioLibraryOnUpdateData)

// An audio item has been removed.
// AudioLibrary.OnRemove.
// Data for AudioLibrary.OnRemove.
type AudioLibraryOnRemoveData struct {
	ID LibraryID `json:"id"`
	// True if the removal is being performed within a transaction.
	Transaction *OptionalBoolean              `json:"transaction,omitempty"`
	Type        NotificationsLibraryAudioType `json:"type"`
}

// AudioLibraryOnRemoveHandler handles AudioLibrary.OnRemove notifications.
type AudioLibraryOnRemoveHandler func(sender string, data AudioLibraryOnRemoveData)

// An audio library scan has started.
// AudioLibrary.OnScanStarted.
// AudioLibraryOnScanStartedData carries the data of AudioLibrary.OnScanStarted.
//
// Schema type: any.

// Scanning the audio library has been finished.
// AudioLibrary.OnScanFinished.
// AudioLibraryOnScanFinishedData carries the data of AudioLibrary.OnScanFinished.
//
// Schema type: any.

// An audio library clean operation has started.
// AudioLibrary.OnCleanStarted.
// AudioLibraryOnCleanStartedData carries the data of AudioLibrary.OnCleanStarted.
//
// Schema type: any.

// The audio library has been cleaned.
// AudioLibrary.OnCleanFinished.
// AudioLibraryOnCleanFinishedData carries the data of AudioLibrary.OnCleanFinished.
//
// Schema type: any.

// An audio library export has finished.
// AudioLibrary.OnExport.
// Data for AudioLibrary.OnExport.
type AudioLibraryOnExportData struct {
	// Default: 0.
	Failcount *int `json:"failcount,omitempty"`
	// Default: .
	File *string `json:"file,omitempty"`
}

// AudioLibraryOnExportHandler handles AudioLibrary.OnExport notifications.
type AudioLibraryOnExportHandler func(sender string, data AudioLibraryOnExportData)

// A video item has been updated.
// VideoLibrary.OnUpdate.
// Data for VideoLibrary.OnUpdate.
type VideoLibraryOnUpdateData struct {
	// True if the update is for a newly added item.
	Added *OptionalBoolean `json:"added,omitempty"`
	ID    LibraryID        `json:"id"`
	// Default: -1.
	Playcount *int `json:"playcount,omitempty"`
	// True if the update is being performed within a transaction.
	Transaction *OptionalBoolean `json:"transaction,omitempty"`
	Type        string           `json:"type"`
}

// VideoLibraryOnUpdateHandler handles VideoLibrary.OnUpdate notifications.
type VideoLibraryOnUpdateHandler func(sender string, data VideoLibraryOnUpdateData)

// A video library export has finished.
// VideoLibrary.OnExport.
// Data for VideoLibrary.OnExport.
type VideoLibraryOnExportData struct {
	// Default: 0.
	Failcount *int `json:"failcount,omitempty"`
	// Default: .
	File *string `json:"file,omitempty"`
	// Default: .
	Root *string `json:"root,omitempty"`
}

// VideoLibraryOnExportHandler handles VideoLibrary.OnExport notifications.
type VideoLibraryOnExportHandler func(sender string, data VideoLibraryOnExportData)

// A video item has been removed.
// VideoLibrary.OnRemove.
// Data for VideoLibrary.OnRemove.
type VideoLibraryOnRemoveData struct {
	ID LibraryID `json:"id"`
	// True if the removal is being performed within a transaction.
	Transaction *OptionalBoolean              `json:"transaction,omitempty"`
	Type        NotificationsLibraryVideoType `json:"type"`
}

// VideoLibraryOnRemoveHandler handles VideoLibrary.OnRemove notifications.
type VideoLibraryOnRemoveHandler func(sender string, data VideoLibraryOnRemoveData)

// A video library scan has started.
// VideoLibrary.OnScanStarted.
// VideoLibraryOnScanStartedData carries the data of VideoLibrary.OnScanStarted.
//
// Schema type: any.

// Scanning the video library has been finished.
// VideoLibrary.OnScanFinished.
// VideoLibraryOnScanFinishedData carries the data of VideoLibrary.OnScanFinished.
//
// Schema type: any.

// A video library clean operation has started.
// VideoLibrary.OnCleanStarted.
// VideoLibraryOnCleanStartedData carries the data of VideoLibrary.OnCleanStarted.
//
// Schema type: any.

// The video library has been cleaned.
// VideoLibrary.OnCleanFinished.
// VideoLibraryOnCleanFinishedData carries the data of VideoLibrary.OnCleanFinished.
//
// Schema type: any.

// The video library has been refreshed and a home screen reload might be necessary.
// VideoLibrary.OnRefresh.
// VideoLibraryOnRefreshData carries the data of VideoLibrary.OnRefresh.
//
// Schema type: any.

// Kodi will be closed.
// System.OnQuit.
// Data for System.OnQuit.
type SystemOnQuitData struct {
	Exitcode int `json:"exitcode"`
}

// SystemOnQuitHandler handles System.OnQuit notifications.
type SystemOnQuitHandler func(sender string, data SystemOnQuitData)

// The system will be restarted.
// System.OnRestart.
// SystemOnRestartData carries the data of System.OnRestart.
//
// Schema type: any.

// The system will be suspended.
// System.OnSleep.
// SystemOnSleepData carries the data of System.OnSleep.
//
// Schema type: any.

// The system woke up from suspension.
// System.OnWake.
// SystemOnWakeData carries the data of System.OnWake.
//
// Schema type: any.

// The system is on low battery.
// System.OnLowBattery.
// SystemOnLowBatteryData carries the data of System.OnLowBattery.
//
// Schema type: any.

// The volume of the application has changed.
// Application.OnVolumeChanged.
// Data for Application.OnVolumeChanged.
type ApplicationOnVolumeChangedData struct {
	Muted  bool `json:"muted"`
	Volume int  `json:"volume"`
}

// ApplicationOnVolumeChangedHandler handles Application.OnVolumeChanged notifications.
type ApplicationOnVolumeChangedHandler func(sender string, data ApplicationOnVolumeChangedData)

// The user is requested to provide some information.
// Input.OnInputRequested.
// Data for Input.OnInputRequested.
type InputOnInputRequestedData struct {
	Title *string `json:"title,omitempty"`
	Type  string  `json:"type"`
	Value string  `json:"value"`
}

// InputOnInputRequestedHandler handles Input.OnInputRequested notifications.
type InputOnInputRequestedHandler func(sender string, data InputOnInputRequestedData)

// The user has provided the requested input.
// Input.OnInputFinished.
// InputOnInputFinishedData carries the data of Input.OnInputFinished.
//
// Schema type: any.

// The screensaver has been activated.
// GUI.OnScreensaverActivated.
// GUIOnScreensaverActivatedData carries the data of GUI.OnScreensaverActivated.
//
// Schema type: any.

// The screensaver has been deactivated.
// GUI.OnScreensaverDeactivated.
// Data for GUI.OnScreensaverDeactivated.
type GUIOnScreensaverDeactivatedData struct {
	Shuttingdown bool `json:"shuttingdown"`
}

// GUIOnScreensaverDeactivatedHandler handles GUI.OnScreensaverDeactivated notifications.
type GUIOnScreensaverDeactivatedHandler func(sender string, data GUIOnScreensaverDeactivatedData)

// Energy saving/DPMS has been activated.
// GUI.OnDPMSActivated.
// GUIOnDPMSActivatedData carries the data of GUI.OnDPMSActivated.
//
// Schema type: any.

// Energy saving/DPMS has been deactivated.
// GUI.OnDPMSDeactivated.
// GUIOnDPMSDeactivatedData carries the data of GUI.OnDPMSDeactivated.
//
// Schema type: any.

// Unresolved references (not present in schema/types.json).
// GUIWindow is a fallback for the unresolved $ref "GUI.Window".
type GUIWindow string

// InputAction is a fallback for the unresolved $ref "Input.Action".
type InputAction string

// NotificationsLibraryAudioType is a fallback for the unresolved $ref "Notifications.Library.Audio.Type".
type NotificationsLibraryAudioType string

// NotificationsLibraryVideoType is a fallback for the unresolved $ref "Notifications.Library.Video.Type".
type NotificationsLibraryVideoType string
